### ISSUE TITLE
Add a templating mechanism to inject variables to produce the report using the markdown template

### ISSUE THREAD

**Issue by timidri** [puppetlabs/pe_tech_check#10]

**Comment by kamiolszewski** [comment]
known concern is structure of support script and contents based on PE version.  Originally when we thought this would only be on newer versions but that isn't the use case

would be easier to have automated for reps.  Could automate the extraction of content to be pasted into google doc. no longer makes sense to use time for full report automation.

**Comment by kamiolszewski** [comment]
use other tooling developed for extraction
