### ISSUE TITLE
Modify the hcl_parse.sh script (see PR) to produce the output required by the chosen transformation tool

### ISSUE THREAD

**Issue by timidri** [puppetlabs/pe_tech_check#12]

**Comment by m0dular** [comment]
@gguillotte What's the current state of `hcl_parse.sh`?  Is there work that still needs to be done on this ticket?  Is markdown the required output format?

**Comment by gguillotte** [comment]
hcl_parse.sh was a script Tom provided to parse content from a support script. I'm rewriting it to collect output required for the report. hcl_parse won't be used. I'm closing this ticket as it was the product of a stand-up two months ago.
