### ISSUE TITLE
Automate conversion of support script content to Markdown working copy

### ISSUE THREAD

**Issue by gguillotte** [puppetlabs/pe_tech_check#20]

**Comment by m0dular** [comment]
@gguillotte Has there been much work done automating the parsing of support script output and making a report out of it?  The version of `hcl_parse.sh` I've seen isn't even syntactically correct, but I also don't understand why we'd choose a shell script that generates markdown.  If this is processing we're doing on our end, we can use more powerful tools.  I make [this repo](https://github.com/m0dular/support-tooling) for a Silver team project, but we could use it for this as well.

For example, we can get a module count per environment:

```
$ ./support_parse.sh modules /tmp/puppet_enterprise_support__pe-201910-master_20190603071406.tar.gz | jq 'map({name, total_modules})'
[
  {
    "name": "develop",
    "total_modules": 41
  },
  {
    "name": "feature",
    "total_modules": 41
  },
  {
    "name": "production",
    "total_modules": 43
  }
]
```
I would be happy to work on this if that's ok, but I wanted to ask where we are on it first.

**Comment by gguillotte** [comment]
I'm working on it, thanks

**Comment by gguillotte** [comment]
the hcl_parse.sh is not what will transform this, will get into more details and update the repo when I get a chance, hopefully today

**Comment by gguillotte** [comment]
Working on getting this into the repo now.

**Comment by m0dular** [comment]
Is there a requirements doc or a WIP for review?  I've already done some of this work in my `support_tooling` repo, we probably don't need to write the same thing twice.

**Comment by kamiolszewski** [comment]
closing due to time to create vs volume we are doing. will revisit when volume increases
