### ISSUE TITLE
Report phrasing suggestions

### ISSUE THREAD

**Issue by kamiolszewski** [puppetlabs/pe_tech_check#23]
received feedback from CSM sources after Duke Energy report for improved phrasing:
the bullet in the beginning that says “Suggest improvements to the Puppet infrastructure that *ensure* problem-free operation” not sure I would use the word ensure. makes it sound like a guarantee

maybe something like “suggest improvements to the Puppet infrastructure that reduce potential problems”  again, just a suggestion

**Comment by kamiolszewski** [comment]
Garrett to look into if this was edited on the template

**Comment by tkishel** [comment]
"to improve the health" would extend the theme

**Comment by gguillotte** [comment]
Updated the report template
