### ISSUE TITLE
use Bolt to run report on older PE versions

### ISSUE THREAD

**Issue by kamiolszewski** [puppetlabs/pe_tech_check#25]
Business Case: some good candidates for HCL (such as customers coming off a 3 year contract term) may be on versions too old to run the HCL module.  In those cases, it would be manual steps to collect metrics and support script.   Research how to deliver automated HCL to older PE versions using Bolt.

@m0dular

**Comment by m0dular** [comment]
@timidri Any updates on this using the version in my PR?

**Comment by timidri** [comment]
@m0dular unfortunately this has been buried under other priorities. I’ll move this to the top of my list.

**Comment by m0dular** [comment]
New PR is [here](https://github.com/puppetlabs/pe_tech_check/pull/31)

**Comment by timidri** [comment]
@m0dular @kamiolszewski Do we have a list of PE versions we would like to test PTC on?

**Comment by m0dular** [comment]
Not sure, but I think it will work on anything > 2014.

**Comment by kamiolszewski** [comment]
This has been done (example Act-On)
