### ISSUE TITLE
Rebrand to PE Tech Check

### ISSUE THREAD

**Issue by gguillotte** [puppetlabs/pe_tech_check#29]
Rebrand the repo, module, and Forge page from Healthcheck Lite to PE Tech Check per @kamiolszewski

**Comment by gguillotte** [comment]
- [X] Rename GH repository to pe_tech_check
- [ ] Update repo contents to reflect rebrand
- [ ] Ship a release as a new module
- [ ] Publish the new module to the Forge
- [ ] Deprecate or remove the old module on the Forge

**Comment by gguillotte** [comment]
PR #28 updates the repo README, tasks, and template.

**Comment by kamiolszewski** [comment]
Done
module updated on forge
