### ISSUE TITLE
Embed or ScreenShot all YAML or code snippet

### ISSUE THREAD

**Issue by MartyEwings** [puppetlabs/pe_tech_check#32]
Feature request to Either Embed code and YAML snippets in the report, or have only an image of code/ YAML

Justification:
In instances where Hiera parameters have been included in the report from the tune script, Due to  copy paste or automatic formatting camel case letters have sometimes replaced the first character in the hiera, this makes the classification invalid, and when copied from the report directly into hiera.yaml files, this may cause unexpected behaviour.

To avoid this, if we could embed code boxes, or use screen captures to force manual transcription from the report, that would resolve the issue

**Comment by kamiolszewski** [comment]
seeing as this report is delivered as a PDF it is surprising that anything would be copied and pasted from it as that is not the intended use. 

tuning recommendations should be acted on by running a pe_tune command and guidance via a support ticket.

closing Issue feature request and can revisit when Marty is back
